version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:15
    container_name: api-solid-pg
    restart: always
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - apisolid-network

volumes:
  postgres_data:

networks:
  apisolid-network:
    driver: bridge
